CREATE TABLE FILE_(
ID NUMBER,
CONSTRAINT ID_FILE PRIMARY KEY (ID),
NAME NVARCHAR2(50) NOT NULL,
FORMAT NVARCHAR2(50) NOT NULL,
SIZE_ NUMBER,
STORAGE_ID NUMBER,
CONSTRAINT ID_STORAGE_FK FOREIGN KEY (STORAGE_ID) REFERENCES STORAGE(ID));